apiVersion: v1
kind: Service
metadata:
  name: devops-portfolio-service
  labels:
    app: devops-portfolio
spec:
  selector:
    app: devops-portfolio
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP  # Change to LoadBalancer or NodePort if external access needed
